###
cakefile to build pong game on gb.

running it is just like a makefile.

to assemble: cake assemble
to link: cake link
to fix: cake fix
to assemble, link and fix: cake build
to clean up build files: cake clean
###

fs = require 'fs'
{exec} = require 'child_process'
{execSync} = require 'child_process'

delete_file = (file) ->
  fs.exists file , (existent) ->
    if existent
      fs.unlink file

execute_program = (program_stuff) ->
  exec program_stuff, (err, stdout, stderr) ->
    process.stdout.write stdout if stdout
    process.stderr.write stderr if stderr


task 'assemble', ->
  execute_program 'rgbasm -o pong.o pong.z80' # run the assembler

task 'link', ->
  execute_program 'rgblink -t -o pong.gb pong.o' # run the linker

task 'fix', ->
  execute_program 'rgbfix -v -t "PONG NICKLAUSW" pong.gb' # fix


task 'build', ->
  execSync 'cake assemble'
  execSync 'cake link'
  execSync 'cake fix'

# clean just gets rid of the object file.
task 'clean', ->
  delete_file('pong.o')
