###
cakefile to build pong game on nes.

running it is just like a makefile.

to assemble: cake assemble
to link: cake link
to assemble and link: cake build
to clean up build files: cake clean
###

fs = require 'fs'
{exec} = require 'child_process'

delete_file = (file) ->
  fs.exists file , (existent) ->
    if existent
      fs.unlinkSync file

execute_program = (program_stuff) ->
  exec program_stuff, (err, stdout, stderr, callback) ->
    process.stdout.write stdout if stdout
    process.stderr.write stderr if stderr
    callback?() if callback


task 'assemble', ->
  execute_program 'ca65 pong.s' # run the assembler

task 'link', ->
  execute_program 'ld65 -C nes.cfg -o pong.nes pong.o' # run the linker


task 'build', ->
  execute_program 'cake assemble'
  execute_program 'cake link'

# clean just gets rid of pong.o
task 'clean', ->
  delete_file('pong.o')
