###
cakefile to build pong game on gb.

running it is just like a makefile.

to build: cake build
to clean up build files: cake clean
###

fs = require 'fs'
{spawnSync} = require 'child_process'

delete_file = (file) ->
    fs.exists file , (existent) ->
      if existent
        fs.unlinkSync file

task 'build', ->
  delete_file 'pong.o' # no previous output

  # run the assembler
  spawnSync 'wla-gb', ['-o', 'pong.z80', 'pong.o'], {stdio:[0,1,2]}

  # run the linker
  spawnSync 'wlalink', ['-vd', 'linkfile', 'pong.gb'], {stdio:[0,1,2]}


# clean just gets rid of pong.o.
task 'clean', ->
  delete_file 'pong.o'
