###
cakefile to build pong game on gb.

running it is just like a makefile.

to assemble: cake assemble
to link: cake link
to assemble and link: cake build
to clean up build files: cake clean
###

fs = require 'fs'
{exec} = require 'child_process'
{execSync} = require 'child_process'

delete_file = (file) ->
    fs.exists file , (existent) ->
      if existent
        fs.unlinkSync file

execute_program = (stuff) ->
  prog = exec stuff, (err, stdout, stderr, callback) ->
    process.stdout.write stdout
    process.stderr.write stderr
    callback?() if callback


task 'assemble', ->
  execute_program 'wla-gb -o pong.z80 pong.o'

task 'link', ->
  fs.openSync 'linkfile', 'w'
  fs.writeFileSync 'linkfile', '[objects]\npong.o\n'

  execute_program 'wlalink -vd linkfile pong.gb'

task 'build', ->
  execSync 'cake assemble'
  execSync 'cake link'


# clean just gets rid of pong.o.
task 'clean', ->
  delete_file 'pong.o'
